In [21]:
import pandas as pd
import sqlite3
import ipywidgets as widgets
from IPython.display import display

## Establecimiento de la conexión

In [22]:
conn = sqlite3.connect('db_empleados_optimizado.sqlite3')

## Leer las categorías profesionales

In [23]:
categorias_profesionales = pd.read_sql_query(
    'SELECT DISTINCT categoria_profesional FROM empleados', conn)
display(categorias_profesionales)

    categoria_profesional
0     Científico de Datos
1         DevOps Engineer
2   Desarrollador Backend
3   Ingeniero de Software
4  Desarrollador Frontend

## Solicitud de datos al usuario (incluye dropdown)

In [40]:
ciudad = input('Introduce la ciudad:')
salario_maximo = input('Introduce el salario máximo:')
desplegable = widgets.Dropdown(
    options=categorias_profesionales['categoria_profesional'].tolist(),
    description='Categorias profesionales:',
    value=categorias_profesionales['categoria_profesional'].iloc[0],
    layout={'width': '300px'}
)
display(desplegable)

Introduce la ciudad:Toledo
Introduce el salario máximo:10000000

Dropdown(description='Categorias profesionales:', layout=Layout(width='300px'), options=('Científico de Datos'…

## Obtención de los datos mediante una sentencia SQL

In [44]:
categoria_profesional = desplegable.value
display(categoria_profesional)
#sql = 'SELECT * FROM empleados WHERE ciudad LIKE ? AND salario<? AND categoria_profesional=?'
#df = pd.read_sql_query(sql, conn, params=(f'%{ciudad}%', salario_maximo, categoria_profesional))
sql = 'SELECT * FROM empleados WHERE ciudad=? AND salario<? AND categoria_profesional=?'
df = pd.read_sql_query(sql, conn, params=(ciudad, salario_maximo, categoria_profesional))
display(df.head())
display(df.info())

'Desarrollador Frontend'

   id  nombre  apellidos   categoria_profesional  ciudad  salario
0  12    Juan    Jiménez  Desarrollador Frontend  Toledo    18894
1  28   Laura       Ruiz  Desarrollador Frontend  Toledo    22994
2  49  Carlos     García  Desarrollador Frontend  Toledo    21051
3  52   Sofía  Fernández  Desarrollador Frontend  Toledo    27600
4  93   Pedro     Alonso  Desarrollador Frontend  Toledo    21443

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     230 non-null    int64
 1   nombre                 230 non-null    object
 2   apellidos              230 non-null    object
 3   categoria_profesional  230 non-null    object
 4   ciudad                 230 non-null    object
 5   salario                230 non-null    int64
dtypes: int64(2), object(4)
memory usage: 10.9+ KB

None

## Almacenamiento de datos en un fichero CSV

In [46]:
df.to_csv('empleados_filtrados.csv', index=False)

## Filtro

In [45]:
empleados_carlos = df[df['nombre']=='Carlos']
display(empleados_carlos)

       id  nombre  apellidos   categoria_profesional  ciudad  salario
2      49  Carlos     García  Desarrollador Frontend  Toledo    21051
59   2492  Carlos  Hernández  Desarrollador Frontend  Toledo    25205
67   2754  Carlos  Hernández  Desarrollador Frontend  Toledo    38762
103  4137  Carlos       Díaz  Desarrollador Frontend  Toledo    38946
105  4277  Carlos       Díaz  Desarrollador Frontend  Toledo    47697
107  4388  Carlos  Fernández  Desarrollador Frontend  Toledo    41318
115  4640  Carlos     Torres  Desarrollador Frontend  Toledo    29618
128  5142  Carlos     Romero  Desarrollador Frontend  Toledo    40704
130  5263  Carlos   Martínez  Desarrollador Frontend  Toledo    38430
146  6259  Carlos    Navarro  Desarrollador Frontend  Toledo    48132
147  6423  Carlos    Navarro  Desarrollador Frontend  Toledo    45714
159  6836  Carlos  Fernández  Desarrollador Frontend  Toledo    25645
163  7011  Carlos  Gutiérrez  Desarrollador Frontend  Toledo    18978
191  8220  Carlos    Jiménez  Desarrollador Frontend  Toledo    28425
204  9108  Carlos     Martín  Desarrollador Frontend  Toledo    22393

In [52]:
# Filtramos los salarios < 30000

df_salarios_bajos = df[(df['salario']>25000) & (df['salario']<30000)]
display(df_salarios_bajos)

       id    nombre  apellidos   categoria_profesional  ciudad  salario
3      52     Sofía  Fernández  Desarrollador Frontend  Toledo    27600
15    658     María   Martínez  Desarrollador Frontend  Toledo    27379
16    700      Luis     Alonso  Desarrollador Frontend  Toledo    26316
18    775    Isabel  Gutiérrez  Desarrollador Frontend  Toledo    28007
21    949    Miguel    Álvarez  Desarrollador Frontend  Toledo    29479
23   1164    Isabel     Martín  Desarrollador Frontend  Toledo    29767
31   1425     María     Torres  Desarrollador Frontend  Toledo    25150
36   1675     Sofía    Sánchez  Desarrollador Frontend  Toledo    27413
43   1961     Sofía     Romero  Desarrollador Frontend  Toledo    26870
45   2004     María    Jiménez  Desarrollador Frontend  Toledo    27709
52   2263     Diego       Ruiz  Desarrollador Frontend  Toledo    28119
59   2492    Carlos  Hernández  Desarrollador Frontend  Toledo    25205
73   3015     Lucía    Jiménez  Desarrollador Frontend  Toledo    27535
78   3118      Luis      Muñoz  Desarrollador Frontend  Toledo    27523
80   3380     Elena     García  Desarrollador Frontend  Toledo    29626
85   3582  Fernando     Romero  Desarrollador Frontend  Toledo    25891
96   3997    Miguel     Martín  Desarrollador Frontend  Toledo    28649
99   4109     Lucía  Gutiérrez  Desarrollador Frontend  Toledo    27946
111  4546     Jorge      López  Desarrollador Frontend  Toledo    25139
112  4581     Clara  Gutiérrez  Desarrollador Frontend  Toledo    26977
115  4640    Carlos     Torres  Desarrollador Frontend  Toledo    29618
123  5030     Diego    Sánchez  Desarrollador Frontend  Toledo    25012
124  5071     Elena      Pérez  Desarrollador Frontend  Toledo    29799
134  5413    Carmen    Navarro  Desarrollador Frontend  Toledo    27195
136  5578    Miguel    Navarro  Desarrollador Frontend  Toledo    26488
153  6632     Pedro    Navarro  Desarrollador Frontend  Toledo    29989
155  6702     Sofía  Hernández  Desarrollador Frontend  Toledo    27589
157  6791     Clara       Díaz  Desarrollador Frontend  Toledo    27245
159  6836    Carlos  Fernández  Desarrollador Frontend  Toledo    25645
161  6904     Paula       Díaz  Desarrollador Frontend  Toledo    29220
164  7067  Fernando      Muñoz  Desarrollador Frontend  Toledo    28300
165  7236     Sofía    Jiménez  Desarrollador Frontend  Toledo    28146
176  7696      Juan     Martín  Desarrollador Frontend  Toledo    27110
181  7922     Sofía  Fernández  Desarrollador Frontend  Toledo    29939
182  7983     María     Martín  Desarrollador Frontend  Toledo    25012
188  8083     Jorge    Sánchez  Desarrollador Frontend  Toledo    25746
191  8220    Carlos    Jiménez  Desarrollador Frontend  Toledo    28425
197  8632      Juan     Torres  Desarrollador Frontend  Toledo    25385
198  8804     María     Torres  Desarrollador Frontend  Toledo    25151
200  8884    Andrés     Torres  Desarrollador Frontend  Toledo    27091
208  9154    Carmen      López  Desarrollador Frontend  Toledo    28282
210  9206    Carmen     Martín  Desarrollador Frontend  Toledo    25441
216  9672      Juan     Torres  Desarrollador Frontend  Toledo    29351
223  9839     Diego     Torres  Desarrollador Frontend  Toledo    29513
226  9872     María     Moreno  Desarrollador Frontend  Toledo    25048
228  9931       Ana    Álvarez  Desarrollador Frontend  Toledo    27478

## Ordenación del DataFrame

In [53]:
empleados_ordenados = df.sort_values(by='salario', ascending=False)
display(empleados_ordenados)

       id  nombre apellidos   categoria_profesional  ciudad  salario
74   3017  Andrés  Martínez  Desarrollador Frontend  Toledo    49969
219  9761   Lucía    Alonso  Desarrollador Frontend  Toledo    49879
171  7467   Clara   Álvarez  Desarrollador Frontend  Toledo    49804
186  8020   Pedro   Álvarez  Desarrollador Frontend  Toledo    49763
90   3845  Miguel   Navarro  Desarrollador Frontend  Toledo    49454
..    ...     ...       ...                     ...     ...      ...
0      12    Juan   Jiménez  Desarrollador Frontend  Toledo    18894
70   2821  Andrés   Navarro  Desarrollador Frontend  Toledo    18833
183  7986   Paula      Ruiz  Desarrollador Frontend  Toledo    18824
75   3029   Laura    García  Desarrollador Frontend  Toledo    18777
20    903   Lucía    Torres  Desarrollador Frontend  Toledo    18576

[230 rows x 6 columns]

## Detección de nulos

In [54]:
display(df.isnull())

        id  nombre  apellidos  categoria_profesional  ciudad  salario
0    False   False      False                  False   False    False
1    False   False      False                  False   False    False
2    False   False      False                  False   False    False
3    False   False      False                  False   False    False
4    False   False      False                  False   False    False
..     ...     ...        ...                    ...     ...      ...
225  False   False      False                  False   False    False
226  False   False      False                  False   False    False
227  False   False      False                  False   False    False
228  False   False      False                  False   False    False
229  False   False      False                  False   False    False

[230 rows x 6 columns]

## Eliminación de nulos (valores faltantes)

In [59]:
df_sin_faltantes = df.dropna(inplace=False) # De todo el DataFrame
df_nombres_sin_faltantes = df['apellidos'].dropna(inplace=False) # Solo de la columna apellidos
display(df_sin_faltantes.head())
display(df_nombres_sin_faltantes.head())

   id  nombre  apellidos   categoria_profesional  ciudad  salario
0  12    Juan    Jiménez  Desarrollador Frontend  Toledo    18894
1  28   Laura       Ruiz  Desarrollador Frontend  Toledo    22994
2  49  Carlos     García  Desarrollador Frontend  Toledo    21051
3  52   Sofía  Fernández  Desarrollador Frontend  Toledo    27600
4  93   Pedro     Alonso  Desarrollador Frontend  Toledo    21443

0      Jiménez
1         Ruiz
2       García
3    Fernández
4       Alonso
Name: apellidos, dtype: object

## Reemplazo de valores faltantes

In [ ]:
df.fillna(value='No disponible', inplace=True)

# Eliminar inconsistencias

In [61]:
df['ciudad'] = df['ciudad'].str.upper()
df.head()

   id  nombre  apellidos   categoria_profesional  ciudad  salario
0  12    Juan    Jiménez  Desarrollador Frontend  TOLEDO    18894
1  28   Laura       Ruiz  Desarrollador Frontend  TOLEDO    22994
2  49  Carlos     García  Desarrollador Frontend  TOLEDO    21051
3  52   Sofía  Fernández  Desarrollador Frontend  TOLEDO    27600
4  93   Pedro     Alonso  Desarrollador Frontend  TOLEDO    21443