## Imports

In [2]:
import sqlite3

import pandas as pd

## Establecimiento de la conexión

In [3]:
conexion = sqlite3.connect('database.db')

## Obtención de los dataframes

In [5]:
df_ccaa = pd.read_sql_query('SELECT * FROM comunidades_autonomas', conexion)
display(df_ccaa)

    id                      nombre
0    1                   Andalucía
1    2                      Aragón
2    3      Principado de Asturias
3    4               Illes Balears
4    5                    Canarias
5    6                   Cantabria
6    7             Castilla y León
7    8          Castilla-La Mancha
8    9                    Cataluña
9   10        Comunitat Valenciana
10  11                 Extremadura
11  12                     Galicia
12  13         Comunidad de Madrid
13  14            Región de Murcia
14  15  Comunidad Foral de Navarra
15  16                  País Vasco
16  17                    La Rioja
17  18     Ceuta (Ciudad Autónoma)
18  19   Melilla (Ciudad Autónoma)

In [7]:
df_provincias = pd.read_sql_query('SELECT * FROM provincias', conexion)
display(df_provincias.head())

   id   nombre  comunidad_autonoma_id
0   1  Almería                    1.0
1   2    Cádiz                    1.0
2   3  Córdoba                    1.0
3   4  Granada                    1.0
4   5   Huelva                    1.0

In [8]:
df_empleados = pd.read_sql_query('SELECT * FROM employees', conexion)
display(df_empleados.head())

   id    name surname1 surname2            job_category   salary  province_id
0   1    Juan     Sanz  Márquez  Conductor/a de Autobús  96305.0         34.0
1   2    Iván    Arias    Calvo   Controller Financiero  33044.0          NaN
2   3  Raquel     Peña  Morales          Carretillero/a  56955.0         50.0
3   4  Noelia  Álvarez     Peña          Guía Turístico  42454.0         31.0
4   5   Paula   Romero    Reyes  Vigilante de Seguridad  76504.0          NaN

## Obtención del nombre, la profesión y el salario de los empleados

In [9]:
df_empleados = pd.read_sql_query('SELECT name, job_category, salary FROM employees', conexion)
display(df_empleados.head())

     name            job_category   salary
0    Juan  Conductor/a de Autobús  96305.0
1    Iván   Controller Financiero  33044.0
2  Raquel          Carretillero/a  56955.0
3  Noelia          Guía Turístico  42454.0
4   Paula  Vigilante de Seguridad  76504.0

## Cierre de la conexión

In [10]:
conexion.close()